sonar.projectKey=kinveetech_AarogyaFrontend
sonar.organization=kinveetech

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.*,**/*.spec.*
sonar.javascript.lcov.reportPaths=coverage/lcov.info
